# Site settings
name: Travelogue
description: '一个最小的，单柱博士的主题，为读者提供了一个身临其境的阅读体验'

baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://yourdomain.com' # the base hostname & protocol for your site

# Build settings
markdown:            kramdown
relative_permalinks: false
permalink:           :title/

pagination:          true
paginate:            8
paginate_path:       page/:num/

author:
    name: 'Salvatore Gentile'
    email: ''
    uri: 'https://github.com/SalGnt'

sass:
    sass_dir: _sass
    style:    compressed

defaults:
  -
      scope:
        path: '_posts'
        type: 'posts'
      values:
        reading_time: true
        # Meta
        show_tags: true
        show_categories: true
        # Social
        share_buttons: true
        disqus: true

gems:
    - jekyll-feed
    - jekyll-sitemap
